import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Box, Button, Grid, Typography } from '@mui/material';
import { useEffect } from 'react';
const inter = Inter({ subsets: ['latin'] });
import { useRouter } from 'next/router';
import Cookie from 'js-cookie';
import ProductCard from '@/Components/card';
import Slider from '@/Components/slider';
import useGetCategory from '@/api/services/useGetCategory';
import Image from 'next/image';
import { Category } from '@/types';
import LocalShippingIcon from '@mui/icons-material/LocalShipping';
import LocalMallIcon from '@mui/icons-material/LocalMall';
import PaymentsIcon from '@mui/icons-material/Payments';
import StoreIcon from '@mui/icons-material/Store';

export default function Home() {
  const { data: allCategory } = useGetCategory();
  console.log(allCategory);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ width: '100%' }}>
        <Slider />
        <Typography sx={{ marginY: '20px' }} align="left" variant="h4">
          دسته بندی ها
        </Typography>
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'space-between',
            width: '100%',
          }}
        >
          {allCategory?.data.categories.map((category: Category) => {
            return (
              <Button
                key={category._id}
                color="secondary"
                variant="contained"
                sx={{ width: '100px', height: '100px', borderRadius: '100%' }}
              >
                <Image
                  src={`http://localhost:8000/images/categories/icons/${category.icon}`}
                  alt=""
                  width={50}
                  height={50}
                />
              </Button>
            );
          })}
        </Box>
        <Box sx={{ display: 'flex', marginY: '50px' }}>
          <Box sx={{ flexGrow: '1' }}>
            <Typography variant="h4" sx={{ width: '300px' }}>
              بهترین خریدرا با ما تجربه کنید
            </Typography>
          </Box>
          <Box
            sx={{
              borderLeft: '2px solid black',
              paddingY: '2px',
              display: 'flex',
              alignItems: 'center',
              paddingX: '20px',
            }}
          >
            <Typography sx={{ opacity: '0.7' }}>
              ما اطمینان میدهیم مشتری های ما بهترین تجربه خرید را داشته باشند
            </Typography>
          </Box>
        </Box>
        <Box
          sx={{ display: 'flex', justifyContent: 'space-around', gap: '10px' }}
        >
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              gap: '5px',
              width: '20%',
            }}
          >
            <Button
              color="secondary"
              variant="contained"
              sx={{ width: '50px', height: '50px' }}
              disabled
            >
              <LocalShippingIcon sx={{ color: 'black' }} />
            </Button>
            <Typography sx={{ fontWeight: 'bold' }}>
              امکان تحویل اکسپرس
            </Typography>
            <Typography sx={{ opacity: '0.7', fontSize: '14px' }}>
              Lorem ipsum dolor sit amet consectetur
            </Typography>
          </Box>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              gap: '5px',
              width: '20%',
            }}
          >
            <Button
              color="secondary"
              variant="contained"
              sx={{ width: '50px', height: '50px' }}
              disabled
            >
              <LocalMallIcon sx={{ color: 'black' }} />
            </Button>
            <Typography sx={{ fontWeight: 'bold' }}>
              ضمانت اصالت کالا
            </Typography>
            <Typography sx={{ opacity: '0.7', fontSize: '14px' }}>
              Lorem ipsum dolor sit amet consectetur
            </Typography>
          </Box>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              gap: '5px',
              width: '20%',
            }}
          >
            <Button
              color="secondary"
              variant="contained"
              sx={{ width: '50px', height: '50px' }}
              disabled
            >
              <PaymentsIcon sx={{ color: 'black' }} />
            </Button>
            <Typography sx={{ fontWeight: 'bold' }}>
              امکان پرداخت درب منزل
            </Typography>
            <Typography sx={{ opacity: '0.7', fontSize: '14px' }}>
              Lorem ipsum dolor sit amet consectetur
            </Typography>
          </Box>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              gap: '5px',
              width: '20%',
            }}
          >
            <Button
              color="secondary"
              variant="contained"
              sx={{ width: '50px', height: '50px' }}
              disabled
            >
              <StoreIcon sx={{ color: 'black' }} />
            </Button>
            <Typography sx={{ fontWeight: 'bold' }}>
              هفت روز ضمانت بازگشت کالا
            </Typography>
            <Typography sx={{ opacity: '0.7', fontSize: '14px' }}>
              Lorem ipsum dolor sit amet consectetur
            </Typography>
          </Box>
        </Box>
      </Box>
    </>
  );
}
